### ISSUE TITLE
zeus unbox vram-getting-started fails

### ISSUE THREAD

**Issue by sgehrman** [liquidapps-io/docs#2]
$ zeus unbox vram-getting-started
⚙️Unboxing: vram-getting-started
Error: not supported yet. pass archive url vram-getting-started
    at _callee2$ (/usr/lib/node_modules/@liquidapps/zeus-cmd/dist/cmds/unbox.js:291:19)
    at tryCatch (/usr/lib/node_modules/@liquidapps/zeus-cmd/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/usr/lib/node_modules/@liquidapps/zeus-cmd/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/lib/node_modules/@liquidapps/zeus-cmd/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/usr/lib/node_modules/@liquidapps/zeus-cmd/dist/cmds/unbox.js:5:191)
    at /usr/lib/node_modules/@liquidapps/zeus-cmd/dist/cmds/unbox.js:5:361

**Comment by NatPDeveloper** [comment]
Hey there, just now spotting this, the zeus repo is a better place for issues like this relating to zeus, can you share:

```
zeus --version
node -v
# what operating system you are on
```

**Comment by NatPDeveloper** [comment]
I'll close this for now as it's been a long time, but feel free to comment after if the error persists.
